apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: cluster-config
spec:
  targetNamespace: mariadb
  releaseName: mariadb
  chart:
    spec:
      chart: mariadb
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: cluster-config
      version: "11.3.5"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    service:
      type: ClusterIP
